
[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[font]
size = 17

[font.glyph_offset]
y = 0
x = 0

[font.normal]
family = "Hack Nerd Font"

[font.offset]
y = 6
x = 0

[[keyboard.bindings]]
key = "Comma"
mods = "Command"

[keyboard.bindings.command]
args = ["-c", "open ~/.config/alacritty/alacritty.yml"]
program = "sh"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[scrolling]
# auto_scroll = true
history = 10000

[window]
decorations = "buttonless"
opacity = 0.95
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5

[general]
# https://github.com/alacritty/alacritty-theme
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
